### ISSUE TITLE
Save Neural network State 

### ISSUE THREAD

**Issue by nazab** [SirTificate/gekko-neuralnet#1]
Hello very nice work
i love the idea of usig neural network for trading bots.
It makes me feels that my bot is running 24/7 but is improving instead of waiting for the right time to buy or sell.

I have a problem with Gekko because sometimes it crash and when this happens I have lost all my trainning done in my neural network.

Would it be possible to store in a file the stat of the neural network and reload it when gekko restart ?

**Comment by Pili21181** [comment]
Hello,
Backtesting results looks great so far but experiencing same issue in live trading.
Was warned in log file https://github.com/askmike/gekko/issues/2033 
Anyway thanks for this tool.
Pili

**Comment by jose-camilo** [comment]
I'm also having that issue on https://github.com/askmike/gekko/issues/2033. I hope they fix it fast because each time it crashes I always loose a lot.

**Comment by CyborgDroid** [comment]
here it is, zuki_nn.js saves nn to a file:

https://github.com/gekkowarez/gekko-neuralnet/tree/master/strategies

**Comment by salbutamolo** [comment]
Hi to all,
I'm a newbie with node, javascript and gekko. I'm trying to configure the zuki_nn strategy to save the training on the "nnfilepath" directory, but i don't understand what the configuration guide means when it says: 

"If you use the UI then clone / rename it will reference the toml file, only thing you will then need to do is copy in the filewriter config. I don't use the ui so i haven't set that up."

Where must i copy/paste the filewriter nnfilepath property? In the UIconfig? In the config for CLI? In the toml file?
I tried to interpreting it but with errors on running gekko. Errors like this:

"uncaughtException TypeError: Cannot read property 'nnfilepath' of undefined"

Could someone show me an example on how to, and where, set the filewriter path correctly?
Thanks in advance.

P.S. I use the UI.

**Comment by goodderek** [comment]
> Hi to all,
> I'm a newbie with node, javascript and gekko. I'm trying to configure the zuki_nn strategy to save the training on the "nnfilepath" directory, but i don't understand what the configuration guide means when it says:
> 
> "If you use the UI then clone / rename it will reference the toml file, only thing you will then need to do is copy in the filewriter config. I don't use the ui so i haven't set that up."
> 
> Where must i copy/paste the filewriter nnfilepath property? In the UIconfig? In the config for CLI? In the toml file?
> I tried to interpreting it but with errors on running gekko. Errors like this:
> 
> "uncaughtException TypeError: Cannot read property 'nnfilepath' of undefined"
> 
> Could someone show me an example on how to, and where, set the filewriter path correctly?
> Thanks in advance.
> 
> P.S. I use the UI.

（explained by bobychain)
If you use the UI:

add filewriter config into web/routes/baseConfig.js

**Comment by rcoenen** [comment]
So when does zuki_nn.js save it's data? continuously? after each trade? 
and how does it "pick up" from a trained data set if you restart the bot after an interruption? (automatically?)

**Comment by rcoenen** [comment]
Also, what if I have multiple paper traders running with zuki_nn? Say I have 1 trading BTC-USD and another BTC-ETH... and I specify via filewriter config to store data in ie. gekko/nn_files/trained.js
Will the BTD-USD trained data not overwrite the BTC-ETC trained data? Or does it automatically write both data sets to the same config file?

**Comment by rcoenen** [comment]
Answering own question: Zuki_NN saves training data only when the Strategy's end() function gets called.
That means it only gets called when a Backtest completes. It never gets called during live trading / paper trading. This is a problem, because imagine I have a bot running with Zuki_NN for a couple of days and Gekko crashes, and I want to resume the trade session without te bot having to have to re-learn from scratch: the bot won't called the end() function and thus will not have saved any training data to resume from.
