### ISSUE TITLE
Live Trading Stops After Few Hours

### ISSUE THREAD

**Issue by BradT7** [SirTificate/gekko-neuralnet#4]
Hello, 
This strategy seems very promising, especially on some back testing results!
The issue I had was running a live strategy and it only trading at progressively slower intervals for about 12-24 hours and then never trade again after that.
I was also running a paper trader too in gekko ui, which showed simulated trades taking place which were not reflective for my live strategy.
I thought the issue might have been multiple instances with live and paper at same time, so I just ran it live from terminal/pm2, but same results, no trades after like 12 hours.
If I restart the live strategy, it will do a few trades at progressively increasing intervals, and then just stop trading again.
I assume a successful live strategy results for yourself. How do you configure, through terminal or gekko ui? Any other ideas? Thanks!

**Comment by SirTificate** [comment]
As I already told you on discord, I suspect that the onTrade() function fails at some point and the bot gets stuck, because the state of this.prevAction is wrong. You could add a debug function which prints this.prevAction every 100 candles or so to see, if there's something wrong.

**Comment by rud3ls87** [comment]
Hello, just checking if this issue was resolved or if there is a potential fix/work around? :) my bot stopped trading after 12hours or so, was working great up till then.

**Comment by questionguy123** [comment]
Were you able to find a fix?

**Comment by questionguy123** [comment]
Maybe something to do with Momentum or Decay settings messing with the learning rate as time goes on? Going to test this now

**Comment by rud3ls87** [comment]
Hey!

No didnt figure it out just yet.

Okay awesome, yes please let me know if you are able to figure it out :) at
the moment im just stopping and restarting the gekko every 10 hours or so.

Regards

Rudy

**Comment by questionguy123** [comment]
According to the 30min of youtube videos i watched, decay will gradually effect the learning rate over time. 

On the backtest:
Changing the learning rate in the backtest effects the outcome
Changing the decay in the backtest has no effect on the outcome

therefore it doesn't make sense how decay can change the learning rate without changing the outcome? Maybe on the live bot decay reduces the learning rate lower and lower until the bot no longer wants to make trades.

30min of youtube doesn't make me an expert but going to try the bot with no decay and will post what happens

**Comment by rud3ls87** [comment]
Fantastic! Thank you for doing the research! Much appreciated.

If you find that the 0 decay works then I will be over the moon :P was
about to write python script to restart the bot every x hours, lol.

Regards

Rudy

**Comment by g1tt** [comment]
I know this is closed but I was experiencing the same problems.
SirTificate's comments on Mar 29th were exactly the cause of my problem.
I have fixed it (a very low-tech fix but it works!) and have created a pull request here -
https://github.com/SirTificate/gekko-neuralnet/pull/11
